AWSTemplateFormatVersion: 2010-09-09
Description: Example Deployment of Service

Parameters:

  CloudFrontCertificateArn:
    Description: wildcard certificate for environment
    Type: String

  ContainerMemory:
    Description: Memory for Container
    Type: Number
    Default: 3768

  ContainerPort:
    Description: Port of Container
    Type: Number
    Default: 8111

  Cluster:
    Description: Name of the ECS Cluster
    Type: String

  ECSSecurityGroup:
    Description: Security Group ID used by ECS Cluster
    Type: String

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  LoadBalancerDomainName:
    Description: Internal DNS name of AWS Load Balancer
    Type: String

  LoadBalancerListenerARN:
    Description: ARN of the Load Balancer Listener
    Type: String

  RDSEndpointAddress:
    Description: DNS name of RDS Database
    Type: String

  ServiceDomainName:
    Description: Domain Name of the Service, for example; upsource.example.com
    Type: String
    Default: teamcity.example.com

  ServiceName:
    Description: Name of the Service
    Type: String
    Default: teamcity

  ServicePriority:
    Description: Priority for Application Load Balancer Listener
    Type: Number
    Default: 8

  VPC:
    Description: VPC Id
    Type: AWS::EC2::VPC::Id

  VPCPrivateSubnets:
    Description: List of subnet ids used for the VPC
    Type: String

Resources:

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref ServiceDomainName
        CacheBehaviors:
          - AllowedMethods: [ GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE ]
            CachedMethods: [ GET, HEAD, OPTIONS ]
            CachePolicyId: !Ref CloudFrontStaticContentPolicy
            Compress: true
            OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 # forward all
            PathPattern: "/s/*"
            SmoothStreaming: false
            TargetOriginId: !Ref ServiceName
            ViewerProtocolPolicy: redirect-to-https
          - AllowedMethods: [ GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE ]
            CachedMethods: [ GET, HEAD, OPTIONS ]
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # cache optimized
            Compress: true
            OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 # forward all
            PathPattern: "/images/*"
            SmoothStreaming: false
            TargetOriginId: !Ref ServiceName
            ViewerProtocolPolicy: redirect-to-https
        DefaultCacheBehavior:
          AllowedMethods: [ GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE ]
          CachedMethods: [ GET, HEAD, OPTIONS ]
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # disable caching
          Compress: true
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3 # forward all
          SmoothStreaming: false
          TargetOriginId: !Ref ServiceName
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 30
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 60
            DomainName: !Ref LoadBalancerDomainName
            Id: !Ref ServiceName
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontCertificateArn
          SslSupportMethod: sni-only

  CloudFrontStaticContentPolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 86400
        MinTTL: 86400
        Name: !Sub ${ServiceName}-static-content-policy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListenerARN
      Priority: !Ref ServicePriority
      Conditions:
        - Field: host-header
          Values: [ !Ref ServiceDomainName ]
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /mnt
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-302
      Port: 80
      Protocol: HTTP
      TargetType: instance
      UnhealthyThresholdCount: 6
      VpcId: !Ref VPC

  Service:
    DependsOn: ListenerRule
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 300
      LaunchType: EC2
      LoadBalancers:
        - ContainerName: !Sub ${ServiceName}
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
      TaskDefinition: !Ref TaskDefinition

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Environment:
            # Memory Configuration
            - Name: TEAMCITY_SERVER_MEM_OPTS
              Value: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
          Essential: true
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-${ServiceName}:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
          Memory: !Ref ContainerMemory
          MountPoints:
            - SourceVolume: efs
              ContainerPath: /data/teamcity_server/datadir
          Name: !Sub ${ServiceName}
          PortMappings:
            - ContainerPort: !Ref ContainerPort
      ExecutionRoleArn: !Ref TaskExecutionRole
      Family: !Sub ${ServiceName}
      TaskRoleArn: !Ref TaskRole
      Volumes:
        - EFSVolumeConfiguration:
            AuthorizationConfig:
              IAM: ENABLED
            FilesystemId: !GetAtt EFS.Outputs.ID
            RootDirectory: /
            TransitEncryption: ENABLED
          Name: efs

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../components/cfn-efs.yaml
      Parameters:
        ECSSecurityGroup: !Ref ECSSecurityGroup
        FilesystemName: !Sub ${ServiceName}
        PrivateSubnets: !Ref VPCPrivateSubnets
        VPC: !Ref VPC

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${ServiceName}
      RetentionInDays: 90

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${ServiceName}-ecs-task-execution-role
      AssumeRolePolicyDocument:
        Statement:
          Action: [ sts:AssumeRole ]
          Effect: Allow
          Principal:
            Service: [ ecs-tasks.amazonaws.com ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: !Sub ${ServiceName}-ecs-task-execution-policy
          PolicyDocument:
            Statement:
              - Action: [ ssm:GetParameters, ssm:GetParameter,
                          secretsmanager:GetSecretValue, secretsmanager:DescribeSecret,
                          kms:Decrypt ]
                Effect: Allow
                Resource: "*"

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${ServiceName}-ecs-task-role
      AssumeRolePolicyDocument:
        Statement:
          Action: [ sts:AssumeRole ]
          Effect: Allow
          Principal:
            Service: [ ecs-tasks.amazonaws.com ]
      Policies:
        - PolicyName: !Sub ${ServiceName}-ecs-task-policy
          PolicyDocument:
            Statement:
              - Action: [ elasticfilesystem:* ]
                Effect: Allow
                Resource: "*"
