AWSTemplateFormatVersion: 2010-09-09
Description: ECR
Parameters:

  RepositoryName:
    Description: Name of the ECR Repository
    Type: String

Resources:

  ECR:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration:
        scanOnPush: false
      RepositoryName: !Ref RepositoryName