AWSTemplateFormatVersion: 2010-09-09
Description: >
  EFS
Parameters:

  ECSSecurityGroup:
    Description: Security Group of ECS
    Type: AWS::EC2::SecurityGroup::Id

  FilesystemName:
    Description: Friendly Name for the file system
    Type: String

  PrivateSubnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  VPC:
    Type: AWS::EC2::VPC::Id

Resources:

  EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      FileSystemPolicy:
        Statement:
          - Action: [ "elasticfilesystem:ClientMount" ]
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
      FileSystemTags:
        - Key: Name
          Value: !Ref FilesystemName
      LifecyclePolicies:
        - TransitionToIA: AFTER_60_DAYS
      PerformanceMode: generalPurpose
      ProvisionedThroughputInMibps: 10
      ThroughputMode: provisioned

  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the ECS hosts and the tasks/containers that run on them
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref ECSSecurityGroup
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: !Sub ${FilesystemName}

  EFSMT1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups: [ !Ref EFSSecurityGroup ]
      SubnetId: !Select [ 0, !Ref PrivateSubnets ]

  EFSMT2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups: [ !Ref EFSSecurityGroup ]
      SubnetId: !Select [ 1, !Ref PrivateSubnets ]

  EFSMT3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SecurityGroups: [ !Ref EFSSecurityGroup ]
      SubnetId: !Select [ 2, !Ref PrivateSubnets ]

Outputs:

  ID:
    Description: Returns the EFS Filesystem ID
    Value: !Ref EFS
