AWSTemplateFormatVersion: 2010-09-09
Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  PublicSubnets:
    Description: Choose which subnets the Application Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed to

Resources:

  LB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref EnvironmentName
      Subnets: !Ref PublicSubnets
      SecurityGroups: [ !Ref SecurityGroup ]
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
      Type: application

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Access to the load balancer that sits in front of ECS
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-LoadBalancers

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-default
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP

Outputs:

  DNSName:
    Description: The URL of the LB
    Value: !GetAtt LB.DNSName

  Listener:
    Description: A reference to a port 80 listener
    Value: !Ref Listener

  SecurityGroup:
    Description: A reference to the security group for load balancers
    Value: !Ref SecurityGroup