AWSTemplateFormatVersion: 2010-09-09
Parameters:

  InstanceType:
    Type: String

  EnvironmentName:
    Type: String

  MultiAZ:
    Type: String
    Default: false
    AllowedValues: [ false, true ]

  PrivateSubnets:
    Description: Choose which subnets this ECS cluster should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  VPC:
    Description: Choose which VPC this ECS cluster should be deployed to
    Type: AWS::EC2::VPC::Id

Resources:

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secret for database user
      GenerateSecretString:
        GenerateStringKey: password
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        PasswordLength: 16
        SecretStringTemplate: '{ "username": "root" }'
      Name: !Sub /${EnvironmentName}/rds/root/credentials

  DB:
    DependsOn: [ DBSecret ]
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 35
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref InstanceType
      DBInstanceIdentifier: !Ref EnvironmentName
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeleteAutomatedBackups: false
      DeletionProtection: false
      EnableIAMDatabaseAuthentication: false
      EnablePerformanceInsights: false
      Engine: mysql
      EngineVersion: 8.0.23
      MasterUsername: !Sub "{{resolve:secretsmanager:${DBSecret}::username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DBSecret}::password}}"
      MultiAZ: !Ref MultiAZ
      PreferredBackupWindow: 03:00-04:00
      PreferredMaintenanceWindow: Sun:08:00-Sun:09:00
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups: [ !Ref SecurityGroup ]

  DBSecretAttachment:
    DependsOn: [ DBSecret, DB ]
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref DB
      TargetType: AWS::RDS::DBInstance

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Security Group for RDS
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub DB Subnet Group for ${EnvironmentName}
      DBSubnetGroupName: !Ref EnvironmentName
      SubnetIds: !Ref PrivateSubnets


Outputs:

  ID:
    Description: Id of the database
    Value: !Ref DB

  EndpointAddress:
    Description: Endpoint address of the database
    Value: !GetAtt DB.Endpoint.Address

  SecurityGroup:
    Description: RDS Security Group
    Value: !Ref SecurityGroup